### ISSUE TITLE
CentOS 8 differences

### ISSUE THREAD

**Issue by FlorianHeigl** [lucascbeyeler/baseline#7]
Hi,

I don't know if you plan on updating your playbooks.
Just in case, here's the things that I found to not work due to changes (`verschlimmbesserungen`) in EL8:

### Packages that don't exist anymore

- ntp (repl. by chrony)
- deltarpm
- libselinux-python
- policycoreutils-python

### Env not matching anymore

- NTP config and driftfile and service restart/enable no longer valid (no ntpd)

**Comment by lucascbeyeler** [comment]
Hi Florian,

Yes I have plans to update. Thanks for that, but if you want you can create the commit and I approve.

**Comment by lucascbeyeler** [comment]
Closing the issue - I made a new release that does support the requested changes.
